ServiceInnovationLab/PresenceChecker

- Procfile
- app.json
- package.json
> Set up server

- config/initializers/devise.rb
> Fix logout links

- app/assets/stylesheets/components.scss
- app/javascript/bundles/Identity/components/Identity.jsx
- app/views/layouts/_header.html.erb
Added link to home pages, invite users.
closes #110
> add a menu

- app/assets/stylesheets/components.scss
fix for presence table alignment
> center align presence table contents

- app/controllers/identities_controller.rb
- spec/controllers/identities_controller_spec.rb
Looked for length of array returned on result, if single, route to page
Closes #106
> If one result, redirect to client#show

- app/services/eligibility_service.rb
- env-example
- spec/spec_helper.rb
* Added a time out
* added caching of Open Fisca response
* Turned on rspec profiling, to report the 10 slowest tests
> Improve open fisca response times and stability

- README.md
I'm not sure if we're looking for more details than this, but here's a start based on the phrasing we use in the Ackama template.
> Small update to clarify what Travis does to deploy the app

- Gemfile
Auto corrected by following Ruby Layout/TrailingWhitespace
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/ruby_configs/32280) to configure it on awesomecode.io
> Auto corrected by following Ruby Layout/TrailingWhitespace

- spec/services/eligibility_service_spec.rb
Auto corrected by following Ruby Style/StringLiterals
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/ruby_configs/32319) to configure it on awesomecode.io
> Auto corrected by following Ruby Style/StringLiterals

- spec/views/layouts/_header.html.haml_spec.rb
- spec/views/layouts/application.html.haml_spec.rb
Auto corrected by following Ruby EmptyLine
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/ruby_config_groups/786) to configure it on awesomecode.io
> Auto corrected by following Ruby EmptyLine

- spec/javascript/packs/application.test.js
Auto corrected by following Javascript Space
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/javascript_config_groups/90) to configure it on awesomecode.io
> Auto corrected by following Javascript Space

- spec/javascript/bundles/Identity/components/Identity.test.js
- spec/javascript/components/PresenceDebugger.test.js
- spec/javascript/components/TimePeriod.test.js
Auto corrected by following Javascript semi
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/javascript_configs/21610) to configure it on awesomecode.io
> Auto corrected by following Javascript semi

- app/javascript/bundles/Identity/components/Identity.jsx
- app/javascript/bundles/Identity/components/KnownIdentity.jsx
- app/javascript/bundles/Presence/components/MovementsTable.jsx
- app/javascript/bundles/Presence/components/PresenceDates.jsx
- app/javascript/bundles/Presence/components/PresenceTable.jsx
- app/javascript/bundles/Presence/components/Year.jsx
- app/javascript/components/PresenceDebugger.jsx
- app/javascript/components/TimePeriod.jsx
- app/javascript/packs/application.js
- spec/javascript/bundles/Identity/components/Identity.test.js
- spec/javascript/bundles/Presence/components/MovementsTable.test.js
- spec/javascript/bundles/Presence/components/PresenceDates.test.js
- spec/javascript/bundles/Presence/components/PresenceTable.test.js
- spec/javascript/bundles/Presence/components/Year.test.js
- spec/javascript/components/PresenceDebugger.test.js
- spec/javascript/components/TimePeriod.test.js
- spec/javascript/packs/application.test.js
- spec/javascript/utilities/utilities.test.js
Auto corrected by following Format Javascript Code
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/javascript_format_config) to configure it on awesomecode.io
> Auto corrected by following Format Javascript Code

- db/seeds.rb
Have done a major clean up of the seed data with the criteria that each result should present some unique case for what we are building
Questions which emerged from this are:
- Should we add `DOB` to the identities table?
- Should we add `Destination to / from` to the movements table?
> Travel to one of the countries counted as NZ (Cook Islands, Niue, Tokelau & Antarctica). *Hazel says: There are rules that come from Legislation that can be automated. This is the Rules part of the engine model. **This is the first piece of work to be done on the project**
- Is ⇧ a thing we need to build ? 
- What is a serial number? What is an identity number? 
part of #221
> Added scenarios from Karyn and cleaned up seed data

- app/javascript/packs/application.js
- app/services/eligibility_service.rb
- db/migrate/20190228021132_add_visa_type_column_to_movements.rb
- db/seeds.rb
- spec/controllers/clients_controller_spec.rb
- test/factories/movements.rb
Added visa_type to the seed data.
> #301 - Added visa_type to the seed data.

- app/assets/stylesheets/components.scss
- app/javascript/bundles/Presence/components/Year.jsx
Added details button to show and hide days in NZ.
Closes #54
> Added details button to show and hide days in NZ.

- app/assets/stylesheets/components.scss
Auto corrected by following Format Css Code
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/css_format_config) to configure it on awesomecode.io
> Auto corrected by following Format Css Code

- app/javascript/packs/application.js
- app/models/visa.rb
- app/models/visa_type.rb
- app/services/eligibility_service.rb
- db/migrate/20190220224611_create_visa_types.rb
- db/migrate/20190221015329_create_visas.rb
- db/schema.rb
- spec/models/movement_spec.rb
- spec/models/visa_spec.rb
- spec/models/visa_type_spec.rb
- test/factories/visa_types.rb
- test/factories/visas.rb
Adds Visa and VisaType models, with basic factories and model tests
closes #195
> Visa and VisaType factories/basic tests

- app/assets/stylesheets/components.scss
- app/javascript/bundles/Presence/components/MovementsTable.jsx
- spec/javascript/bundles/Presence/components/MovementsTable.test.js
- spec/javascript/bundles/Presence/components/__snapshots__/MovementsTable.test.js.snap
Add visa type to movements table UI
> Add visa type to movements table UI

- app/models/movement.rb
- app/services/eligibility_service.rb
- spec/models/movement_spec.rb
Using this branch since other one closed and couldn't reopen it!
closes #316
> update eligibility service to use direction methods

- app/services/eligibility_service.rb
Auto corrected by following Lint Ruby TrailingComma
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/ruby_config_groups/955) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby TrailingComma

- app/models/visa_type.rb
Auto corrected by following Lint Ruby Layout/TrailingWhitespace
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/PresenceChecker/ruby_lint_configs/32280) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby Layout/TrailingWhitespace

- .travis.yml
The tests are all failing! This should help them to pass.
> Use port 5432 instead of 5433 for Postgres
